/*generated by KMC*/
KISSY.config('modules', {
 'my/adder': { requires: ['my/adder.css']},
 'my/index': { requires: ['my/index.css', 'event', 'my/adder', 'my/index-xtpl', 'dom','xtemplate/runtime']} 
});