/*generated by KMC*/
KISSY.config('modules', {
 'my/adder': { requires: ['my/adder.css']},
 'my/index': { requires: ['my/index.css', 'event/dom', 'my/adder', 'xtemplate/runtime', 'my/index-xtpl', 'dom']} 
});